// generated by tools/tileset_gen.py

#pragma once

#include <SFML/System.hpp>

#include "spriteinfo.hpp"

namespace Tileset {

const SpriteInfo alien_NE = { 31, 47, { sf::Vector2f(0, 0), sf::Vector2f(31, 0), sf::Vector2f(31, 47), sf::Vector2f(0, 47) } };
const SpriteInfo alien_NW = { 31, 47, { sf::Vector2f(31, 0), sf::Vector2f(62, 0), sf::Vector2f(62, 47), sf::Vector2f(31, 47) } };
const SpriteInfo alien_SE = { 31, 47, { sf::Vector2f(62, 0), sf::Vector2f(93, 0), sf::Vector2f(93, 47), sf::Vector2f(62, 47) } };
const SpriteInfo alien_SW = { 31, 47, { sf::Vector2f(93, 0), sf::Vector2f(124, 0), sf::Vector2f(124, 47), sf::Vector2f(93, 47) } };
const SpriteInfo astronaut_SE = { 31, 47, { sf::Vector2f(124, 0), sf::Vector2f(155, 0), sf::Vector2f(155, 47), sf::Vector2f(124, 47) } };
const SpriteInfo astronaut_SW = { 31, 47, { sf::Vector2f(155, 0), sf::Vector2f(186, 0), sf::Vector2f(186, 47), sf::Vector2f(155, 47) } };
const SpriteInfo astronaut_NW = { 31, 47, { sf::Vector2f(186, 0), sf::Vector2f(217, 0), sf::Vector2f(217, 47), sf::Vector2f(186, 47) } };
const SpriteInfo astronaut_NE = { 31, 47, { sf::Vector2f(217, 0), sf::Vector2f(248, 0), sf::Vector2f(248, 47), sf::Vector2f(217, 47) } };
const SpriteInfo metalTileConnectStraight_NE = { 76, 56, { sf::Vector2f(248, 0), sf::Vector2f(324, 0), sf::Vector2f(324, 56), sf::Vector2f(248, 56) } };
const SpriteInfo metalTileConnectSide_NW = { 76, 55, { sf::Vector2f(324, 0), sf::Vector2f(400, 0), sf::Vector2f(400, 55), sf::Vector2f(324, 55) } };
const SpriteInfo metalTileConnectCornerInner_SW = { 76, 54, { sf::Vector2f(400, 0), sf::Vector2f(476, 0), sf::Vector2f(476, 54), sf::Vector2f(400, 54) } };
const SpriteInfo metalTileConnectCornerInner_NW = { 76, 54, { sf::Vector2f(476, 0), sf::Vector2f(552, 0), sf::Vector2f(552, 54), sf::Vector2f(476, 54) } };
const SpriteInfo metalTileConnectSide_SW = { 76, 54, { sf::Vector2f(552, 0), sf::Vector2f(628, 0), sf::Vector2f(628, 54), sf::Vector2f(552, 54) } };
const SpriteInfo metalTileConnectStraight_NW = { 76, 56, { sf::Vector2f(628, 0), sf::Vector2f(704, 0), sf::Vector2f(704, 56), sf::Vector2f(628, 56) } };
const SpriteInfo metalTileConnectCenter_NE = { 75, 54, { sf::Vector2f(704, 0), sf::Vector2f(779, 0), sf::Vector2f(779, 54), sf::Vector2f(704, 54) } };
const SpriteInfo metalTileConnectEnd_SW = { 72, 54, { sf::Vector2f(779, 0), sf::Vector2f(851, 0), sf::Vector2f(851, 54), sf::Vector2f(779, 54) } };
const SpriteInfo metalTileConnectEnd_NW = { 72, 54, { sf::Vector2f(851, 0), sf::Vector2f(923, 0), sf::Vector2f(923, 54), sf::Vector2f(851, 54) } };
const SpriteInfo metalTileConnectCornerInner_NE = { 72, 56, { sf::Vector2f(923, 0), sf::Vector2f(995, 0), sf::Vector2f(995, 56), sf::Vector2f(923, 56) } };
const SpriteInfo metalTileConnectCornerInner_SE = { 72, 56, { sf::Vector2f(995, 0), sf::Vector2f(1067, 0), sf::Vector2f(1067, 56), sf::Vector2f(995, 56) } };
const SpriteInfo metalTileConnectEnd_NE = { 72, 54, { sf::Vector2f(1067, 0), sf::Vector2f(1139, 0), sf::Vector2f(1139, 54), sf::Vector2f(1067, 54) } };
const SpriteInfo metalTileConnectSide_NE = { 76, 55, { sf::Vector2f(1139, 0), sf::Vector2f(1215, 0), sf::Vector2f(1215, 55), sf::Vector2f(1139, 55) } };
const SpriteInfo metalTileConnectEnd_SE = { 72, 54, { sf::Vector2f(1215, 0), sf::Vector2f(1287, 0), sf::Vector2f(1287, 54), sf::Vector2f(1215, 54) } };
const SpriteInfo metalTileConnectSide_SE = { 76, 55, { sf::Vector2f(1287, 0), sf::Vector2f(1363, 0), sf::Vector2f(1363, 55), sf::Vector2f(1287, 55) } };
const SpriteInfo spaceCraft3_NE = { 78, 58, { sf::Vector2f(1363, 0), sf::Vector2f(1441, 0), sf::Vector2f(1441, 58), sf::Vector2f(1363, 58) } };
const SpriteInfo metalFenceCorner_SW = { 36, 58, { sf::Vector2f(1441, 0), sf::Vector2f(1477, 0), sf::Vector2f(1477, 58), sf::Vector2f(1441, 58) } };
const SpriteInfo metalFenceCorner_NW = { 36, 58, { sf::Vector2f(1477, 0), sf::Vector2f(1513, 0), sf::Vector2f(1513, 58), sf::Vector2f(1477, 58) } };

}
