// generated by tools/tileset_gen.py

#pragma once

#include <SFML/System.hpp>

#include "spriteinfo.hpp"

namespace Tileset {

const SpriteInfo alien_NE = { 31, 47, { sf::Vector2f(0, 0), sf::Vector2f(31, 0), sf::Vector2f(31, 47), sf::Vector2f(0, 47) } };
const SpriteInfo alien_NW = { 31, 47, { sf::Vector2f(31, 0), sf::Vector2f(62, 0), sf::Vector2f(62, 47), sf::Vector2f(31, 47) } };
const SpriteInfo alien_SE = { 31, 47, { sf::Vector2f(62, 0), sf::Vector2f(93, 0), sf::Vector2f(93, 47), sf::Vector2f(62, 47) } };
const SpriteInfo alien_SW = { 31, 47, { sf::Vector2f(93, 0), sf::Vector2f(124, 0), sf::Vector2f(124, 47), sf::Vector2f(93, 47) } };
const SpriteInfo astronaut_SE = { 31, 47, { sf::Vector2f(124, 0), sf::Vector2f(155, 0), sf::Vector2f(155, 47), sf::Vector2f(124, 47) } };
const SpriteInfo astronaut_SW = { 31, 47, { sf::Vector2f(155, 0), sf::Vector2f(186, 0), sf::Vector2f(186, 47), sf::Vector2f(155, 47) } };
const SpriteInfo astronaut_NW = { 31, 47, { sf::Vector2f(186, 0), sf::Vector2f(217, 0), sf::Vector2f(217, 47), sf::Vector2f(186, 47) } };
const SpriteInfo astronaut_NE = { 31, 47, { sf::Vector2f(217, 0), sf::Vector2f(248, 0), sf::Vector2f(248, 47), sf::Vector2f(217, 47) } };
const SpriteInfo metalTileConnectStraight_NE = { 76, 56, { sf::Vector2f(248, 0), sf::Vector2f(324, 0), sf::Vector2f(324, 56), sf::Vector2f(248, 56) } };
const SpriteInfo metalTileConnectSide_NW = { 76, 55, { sf::Vector2f(324, 0), sf::Vector2f(400, 0), sf::Vector2f(400, 55), sf::Vector2f(324, 55) } };
const SpriteInfo metalTileConnectCornerInner_SW = { 76, 54, { sf::Vector2f(400, 0), sf::Vector2f(476, 0), sf::Vector2f(476, 54), sf::Vector2f(400, 54) } };
const SpriteInfo metalTileConnectCornerInner_NW = { 76, 54, { sf::Vector2f(0, 56), sf::Vector2f(76, 56), sf::Vector2f(76, 110), sf::Vector2f(0, 110) } };
const SpriteInfo metalTileConnectSide_SW = { 76, 54, { sf::Vector2f(76, 56), sf::Vector2f(152, 56), sf::Vector2f(152, 110), sf::Vector2f(76, 110) } };
const SpriteInfo metalTileConnectStraight_NW = { 76, 56, { sf::Vector2f(152, 56), sf::Vector2f(228, 56), sf::Vector2f(228, 112), sf::Vector2f(152, 112) } };
const SpriteInfo metalTileConnectCenter_NE = { 75, 54, { sf::Vector2f(228, 56), sf::Vector2f(303, 56), sf::Vector2f(303, 110), sf::Vector2f(228, 110) } };
const SpriteInfo metalTileConnectEnd_SW = { 72, 54, { sf::Vector2f(303, 56), sf::Vector2f(375, 56), sf::Vector2f(375, 110), sf::Vector2f(303, 110) } };
const SpriteInfo metalTileConnectEnd_NW = { 72, 54, { sf::Vector2f(375, 56), sf::Vector2f(447, 56), sf::Vector2f(447, 110), sf::Vector2f(375, 110) } };
const SpriteInfo metalTileConnectCornerInner_NE = { 72, 56, { sf::Vector2f(0, 112), sf::Vector2f(72, 112), sf::Vector2f(72, 168), sf::Vector2f(0, 168) } };
const SpriteInfo metalTileConnectCornerInner_SE = { 72, 56, { sf::Vector2f(72, 112), sf::Vector2f(144, 112), sf::Vector2f(144, 168), sf::Vector2f(72, 168) } };
const SpriteInfo metalTileConnectEnd_NE = { 72, 54, { sf::Vector2f(144, 112), sf::Vector2f(216, 112), sf::Vector2f(216, 166), sf::Vector2f(144, 166) } };
const SpriteInfo metalTileConnectSide_NE = { 76, 55, { sf::Vector2f(216, 112), sf::Vector2f(292, 112), sf::Vector2f(292, 167), sf::Vector2f(216, 167) } };
const SpriteInfo metalTileConnectEnd_SE = { 72, 54, { sf::Vector2f(292, 112), sf::Vector2f(364, 112), sf::Vector2f(364, 166), sf::Vector2f(292, 166) } };
const SpriteInfo metalTileConnectSide_SE = { 76, 55, { sf::Vector2f(364, 112), sf::Vector2f(440, 112), sf::Vector2f(440, 167), sf::Vector2f(364, 167) } };
const SpriteInfo spaceCraft3_NE = { 78, 58, { sf::Vector2f(0, 168), sf::Vector2f(78, 168), sf::Vector2f(78, 226), sf::Vector2f(0, 226) } };
const SpriteInfo metalFenceCorner_SW = { 36, 58, { sf::Vector2f(78, 168), sf::Vector2f(114, 168), sf::Vector2f(114, 226), sf::Vector2f(78, 226) } };
const SpriteInfo metalFenceCorner_NW = { 36, 58, { sf::Vector2f(114, 168), sf::Vector2f(150, 168), sf::Vector2f(150, 226), sf::Vector2f(114, 226) } };

}
